version: '3.7'

services:
  frontend:
    image: public.ecr.aws/h2s4i0x5/mock-ai-interviewer-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: public.ecr.aws/h2s4i0x5/mock-ai-interviewer-backend:latest
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_ORGANIZATION: ${OPENAI_ORGANIZATION}
      OPENAI_MODEL: ${OPENAI_MODEL}
      LLM_REVIEW_PROMPT: ${LLM_REVIEW_PROMPT}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      ELEVEN_LABS_API_KEY: ${ELEVEN_LABS_API_KEY}
      GOOGLE_SA_PRIVATE_KEY: ${GOOGLE_SA_PRIVATE_KEY}
      GOOGLE_SA_PRIVATE_KEY_ID: ${GOOGLE_SA_PRIVATE_KEY_ID}
