name: Build Containers
run-name: ${{ github.actor }} is building Docker Containers 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Building Docker Compose Containers
        run: docker-compose -f docker-compose.local.yml build
      - run: echo "🍏 This job's status is ${{ job.status }}."
