name: Test AWS Connection
run-name: ${{ github.actor }} is testing AWS Connection 🧪
on: []
jobs:
  deploy:
    name: Testing AWS Connection
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::306210296691:role/GitHubActionsECRPushPull
          aws-region: us-east-1
      - name: Test AWS Connection
        run: |
          aws sts get-caller-identity
      - name: List repositories
        run: |
          aws ecr-public describe-repositories
